### ISSUE TITLE
Any plan on releasing a new minor / patch version?

### ISSUE THREAD

**Issue by Gilwe** [go-gormigrate/gormigrate#125]
The current version 2.0.0 is still using `gorm.io/gorm v1.20.0` which is the version I'm using.
I want to upgrade my gorm to its latest (1.23.4) but it isn't 100% compatible with gormigrate v2.0.0.

Is it possible to release a new version please?

**Comment by andreynering** [comment]
Hi @Gilwe,

Sorry for wait, and thanks for the suggestion.

I just released [v2.0.1](https://github.com/go-gormigrate/gormigrate/releases/tag/v2.0.1).
