### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by wild-endeavor** [go-gormigrate/gormigrate#14]
This is not an issue, just a question.

The demo code has a comment saying that we should copy the struct corresponding to a table to the migration function itself.  This makes sense to me.

However, what if I'm trying to make a model/table that has a foreign key to another table, which has a key to another table, which has a foreign key to a fourth table.  It doesn't seem quite right to have a bunch of copies of every struct, with every migration.

What's the recommended pattern here?

**Comment by andreynering** [comment]
Hi @wild-endeavor,

You should copy only the foreign key fields, not the models

So, as example, if you have a `Pet` relation that references `Human`, you'd have this

```go
type Pet {
        ID int
        HumanID int
        Name string
}
```

and not this

```go
type Pet {
        ID int
        HumanID int
        Name string

        Human *Human
}
```

And about creating the foreign key itself, referencing the model is not necessary: http://gorm.io/docs/migration.html#Add-Foreign-Key

**Comment by wild-endeavor** [comment]
thanks!
