### ISSUE TITLE
Init schema applies few times

### ISSUE THREAD

**Issue by silence44** [go-gormigrate/gormigrate#16]
In my app I have for right now only initSchema function and no migrations.

```
func (g *Gormigrate) isFirstRun() bool {
	var count int
	g.db.
		Table(g.options.TableName).
		Count(&count)
	return count == 0
}
```
As I understand this function calculates amount of migrations executed before. But in my case it always 0 and that is causing error on 2nd launch of application.

**Comment by andreynering** [comment]
Hi @silence44,

If you really don't want to have any migrations, I recommend you to add a dummy migration with an empty `func() error { return nil }`.

You're not supposed to have no migrations. Actually, I consider it a bug, and it should return an error if there's no migration in the list.

**Comment by silence44** [comment]
If you just started developing your application, then you going to have only init schema for some time. And I think this it is bug that initSchema executes every time on app start. Especially when the reason of this is no other migrations provided.

I can create PR to fix this if you don't mind.

**Comment by andreynering** [comment]
@silence44 I already change the code to don't allow an empty migration list. What would you propose to allow it and don't run initSchema once?

IMHO the right approach is to create migrations with the initial schema and only add an initSchema func once you have a good number of them.
