### ISSUE TITLE
Failed to migrate if no migration is defined

### ISSUE THREAD

**Issue by pverschuure** [go-gormigrate/gormigrate#17]
Hi,

I have the following code:

```
m := gormigrate.New(d.db, gormigrate.DefaultOptions, []*gormigrate.Migration{})

m.InitSchema(func(tx *gorm.DB) error {
	return tx.AutoMigrate(
		&MyTable{},
	).Error
})

if err := m.Migrate(); err != nil {
	log.Fatalf("Could not migrate: %v", err)
}
```

When I run this I get the following error:
`
Could not migrate: gormigrate: No migration defined
`

This happens because the following line of code (which was recently introduced I believe):
https://github.com/go-gormigrate/gormigrate/blob/master/gormigrate.go#L121-L123

Could you fix this please?

**Comment by andreynering** [comment]
Hi @PeterVerschuure,

What's your use case for having an empty migration list? That's not supported, because we can't know if any migration was ever run before (to prevent `InitSchema` for running twice!)

You should start by writing your migration code into proper migrations, or in the worst case add a dummy migration (with `func() error { return nil }`) so we have something on the database.

**Comment by andreynering** [comment]
@pverschuure Closing for lack of feedback.

If you have more thoughts, feel free to comment here.

**Comment by ilmaruk** [comment]
Hi @andreynering ; I've stumbled upon this very same issue and my reason for having something similar (i.e.: an `InitSchema`, but no migrations) is that I'm currently happy with the schema I have, which I consider the _base-line_ for my (new) application, but I'm foreseeing there may be changes in the future.
So, the _base-line_ would be applied only to new/clean databases and any following migration would be applied "normally".

I appreciate a dummy migration would do (which is probably what I'm going to do now), but IMHO it's not an elegant solution (i.e.: it would require an explicit comment to explain why I'm adding it).

As you said, in this scenario, `InitSchema` would be always executed, as long as the migrations table is empty, but then why not entering a specific (reserved) ID into migrations, once `InitSchema` is executed correctly? That wouldn't tamper with the current migration schema.

Happy to discuss this further and contribute to any agreed solution.

**Comment by andreynering** [comment]
Hi @ilmaruk,

Indeed your proposal seems reasonable to me.

Logic could be like:

- If `InitSchema` is ran and we have migrations on the list, insert them all on the migrations table (that's already the current behavior);
- If `InitSchema` is ran and we have no migrations on the list, insert a special ID to the table.

So yeah, I'd be happy to review a PR for it, with the proper tests written.
