### ISSUE TITLE
Maintenance status of this project (2023)?

### ISSUE THREAD

**Issue by omarkohl** [go-gormigrate/gormigrate#180]
This library looks great, thank you! As someone who is considering start using it I am a little worried about the maintenance status. Could someone comment on this? At the time of writing (Feb 2023) it seems that there has been no release with features/bugfixes in 3 years (only two releases updating dependencies), there are several large PRs open without any comments or explanations ... :thinking: 

This is not meant as a criticism towards the maintainers but as guidance for people considering using this project!

**Comment by andreynering** [comment]
Hi @omarkohl,

I indeed lost interest in this project. I don't use it anymore, and given I maintain other OSS projects, and have little to no time to dedicate to this one.

**Comment by omarkohl** [comment]
Hi @andreynering,

that's unfortunate but understandable. Thank you for the quick and honest answer!

Maybe you want to consider adding a note to the README to make the situation clear to others as well.

**Comment by dgunay** [comment]
I have been using it in production at work and it so far hasn't really produced any surprises. If you want anything special out of it, just fork it and maintain it yourself. The codebase is tiny (~700 SLOC in Go). Not a terribly huge burden to take on.

**Comment by andreynering** [comment]
Due to my lack of interest and time to work on this project and the fact that there is no other maintainer, I decided to archive this repository.

I hope everybody understand. I encourage anyone who needs changes to fork the repository or vendor the package.
