### ISSUE TITLE
Validating the migration ID exist in the list of migrations

### ISSUE THREAD

**Issue by tonytanger** [go-gormigrate/gormigrate#20]
With `MigrateTo(migrationID)` if `migrationID` does not exist in the list of migrations, gormigrate will migrate to the latest migration like `MigrateTo("")`. Similarly, `RollbackTo(migrationID)` will also rollback all migrations if the `migrationID` does not exist. So a simple typo will have catastrophic consequences.

It seems to make more sense for the desired effect to return an error when the `migrationID` does not exist. `MigrateTo` already checks for `checkDuplicatedID`. We can add something like `checkIDExist` to `MigrateTo` and `RollbackTo` as such

```
// ErrMigrationIDDoesNotExist is returned when migrating or rolling back to a migration ID that
// does not exist in the list of migrations
var ErrMigrationIDDoesNotExist = errors.New("gormigrate: Tried to migrate to an ID that doesn't exist")

func (g *Gormigrate) checkIDExist(migrationID string) error {
	if migrationID == "" {
		return nil
	}
	for _, migrate := range g.migrations {
		if migrate.ID == migrationID {
			return nil
		}
	}
	return ErrMigrationIDDoesNotExist
}
```

**Comment by andreynering** [comment]
Closed by #21
