### ISSUE TITLE
Improve readme for more gomodules clarity

### ISSUE THREAD

**Issue by martijnjanssen** [go-gormigrate/gormigrate#24]
I'm using gormigrate in a project, but I'm encountering some difficulties with importing the package. The readme could be of more help in this instance.

The error I'm getting is:
```
go: github.com/go-gormigrate/gormigrate@v1.3.0: parsing go.mod: unexpected module path "gopkg.in/gormigrate.v1"
go: error loading module requirements
```
Which is possibly a conflict in import urls, but changing over ALL import paths doesn't really sound that normal to me like in issue #22.

**Comment by martijnjanssen** [comment]
Okay nevermind, the issue was that some way or the other, auto-import imported the GitHub version instead of the gopkg.in version in the file. After changing this to the gopkg.in import, all was fine and resolved.

**Comment by andreynering** [comment]
@martijnjanssen 👍

Thanks for posting how you solved it. That helps in case anyone else also have the problem. 🙂

**Comment by noamt** [comment]
May I suggest re-opening this issue?
I believe it's `gormigrate`'s responsibility to change `testify`'s namespace to github.

`testify`'s "official" [installation instructions](https://github.com/stretchr/testify#installation) use github, not gopkin.

I would like to use `gormigrate`, but my project is huge and already uses testify, and it's not realistic that I change all my project files.

WDYT? May I open a pull request?

**Comment by andreynering** [comment]
@noamt Hmm... OK. I haven't noticed that `testify` is the real issue here. I think I misunderstood things.

In that case, yes, I'd be happy to review a PR for it.

That said, (1) it's strange that Go doesn't allow importing testify from both `gopkg` and `github` and (2) changing the import path on this project should then break things for at least the two users that reported this issue here.

**Comment by noamt** [comment]
@andreynering It's true that things will break on the next upgrade, yes

**Comment by martijnjanssen** [comment]
For me, the issue was only gormigrate, testify had nothing to do with it. My issue was only the error message in the PR description. I would suggest opening another issue with the problem @noamt is encountering, since it doesn't really sound that related or equal.

**Comment by noamt** [comment]
@martijnjanssen You're right that it's not directly related. In any case, opened PR #26
