### ISSUE TITLE
How about get the create table sql without real connection ?

### ISSUE THREAD

**Issue by Astone-Chou** [go-gormigrate/gormigrate#29]

**Comment by andreynering** [comment]
Hi @Astone-Chou,

Can you explain exactly your use case for wanting that?

Also, are you talking about the `migrations` table or another table you want to create inside a migration?

**Comment by Astone-Chou** [comment]
I want to get the create sql script without mysql server (offline).  In live enviroment mysql. i didn't have the priviledge to create a table.

**Comment by andreynering** [comment]
@Astone-Chou If you're talking about Gorm's `AutoMigrate` function, you should actually open an issue on [the Gorm repository](https://github.com/jinzhu/gorm) asking for this feature.

Gormigrate is just a wrapper to Gorm.

I'm closing this for now, but feel free to comment if you have thoughts.
