### ISSUE TITLE
Noisy log message `transaction has already been committed or rolled back` during regular usage

### ISSUE THREAD

**Issue by j16r** [go-gormigrate/gormigrate#36]
Since we use this pattern:

```go
tx.begin()
defer tx.rollback()
```

This means rollback is called even when a transaction is committed. This log message is mostly harmless, but it makes it difficult to properly diagnose improper use of transactions in our code base.

![Screen Shot 2019-04-30 at 13 14 19](https://user-images.githubusercontent.com/344071/56987168-e9c07680-6b49-11e9-88f2-748bd9d73039.png)

Other than doing:

```go
tx.begin()
if err != nil {
  tx.rollback()
  return err
}
return tx.commit()
```

Maybe this could be handled by suppressing logging from gormigrate's use of `rollback` or by checking if a commit has already been run and turning `rollback` into a no-op. Thoughts?

**Comment by andreynering** [comment]
Hi @j16r,

This pattern of using `defer` for rollback is permitted by the standard library's `database/sql` package. It's *intended* to be used like this. It just returns `sql.ErrTxDone` without any side effects.

So it's sad that Gorm doesn't recognize this pattern. But I think it'd be easy to fix it [here](https://github.com/jinzhu/gorm/blob/e3987fd4b803c16497aa4dfd2e75db7a6a061a4e/main.go#L525) and [here](https://github.com/jinzhu/gorm/blob/e3987fd4b803c16497aa4dfd2e75db7a6a061a4e/main.go#L536).

From

```go
s.AddError(db.Rollback())
```

To

```go
if err := db.Rollback(); err != nil && err != sql.TxDone {
	s.AddError(err)
}
```

What do you think? We could propose a PR to Gorm, and in case they don't accept it, we could do some logic on our side to keep track of the transaction state.

**Comment by j16r** [comment]
Sounds good, there are some other logging issues I'd like to address in gorm so I'll issue a PR there.

**Comment by andreynering** [comment]
@j16r Can this be closed now? 🙂
