### ISSUE TITLE
Add ability to rollback all migrations

### ISSUE THREAD

**Issue by leoleoasd** [go-gormigrate/gormigrate#44]
This is a great package and it had helped me a lot. But, the missing ability to "rollback all migrations" have been troubling me for a while.
If I run `RollbackTo` with the first migration's id, it will keep the first migration unrolled. I can only call `RollbackLast` multiple times or call it after `RollbackTo` the first migration. 
This feature is needed when we want to clean the database and rebuild a fresh new one. While developing an application, this is a common need by developers. A simple method `RollbackAll` would be nice.

**Comment by andreynering** [comment]
Hi @leoleoasd, thanks for opening this issue!

I'm not sure about this. Rollbacking all migrations is not what people should do most of the time. If you want a clean database, you should probably delete and re-create it.

In a real world scenario an app can have hundreds or thousands of migrations, and rollbacking many of them can both slow and unpredictable.

**Comment by leoleoasd** [comment]
I only need this feature for debugging purposes, for example, remove all tables without opening my database client.
I have a workaround for this: just add a migration which does nothing at very first, then roll back to that migration. This is working, but surely, not elegant. So, for me, it would be nice to have this feature, but if others don't need it, it's ok for me to use the workaround mentioned above.
