### ISSUE TITLE
jinzhu/gorm to github.com/go-gorm/gorm/

### ISSUE THREAD

**Issue by exfly** [go-gormigrate/gormigrate#45]

**Comment by andreynering** [comment]
Hi @exfly,

I was not aware of this change, since I don't use Gorm often anymore (even that I maintain this lib). Do you have any links to any issues of documentation about this change?

The problem is that changing the import path is a breaking change, and would require planning a new release.

**Comment by exfly** [comment]
ref: https://github.com/go-gorm/gorm/issues/2886 .Any help?

**Comment by 103cuong** [comment]
any updates?
`Cannot use 'db' (type *"gorm.io/gorm".DB) as type *"github.com/jinzhu/gorm".DB`

**Comment by andreynering** [comment]
This is now released as v2 in a new import path: `github.com/go-gormigrate/gormigrate/v2`
