### ISSUE TITLE
migration table create failed in mysql database with utf8mb4 charset

### ISSUE THREAD

**Issue by heww** [go-gormigrate/gormigrate#6]
`CREATE TABLE %s (%s VARCHAR(255) PRIMARY KEY)` this will failed for in utf8mb4 database of mysql the max key length limit to 171 chars

```
Error 1071: Specified key was too long; max key length is 767 bytes
```

**Comment by dseevr** [comment]
In case anyone else hits this, you need to set `innodb_large_prefix=1` or upgrade to MySQL 5.7+
